<a href="https://colab.research.google.com/github/twisha-k/Python_notes/blob/main/56_coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 56: OOP - Polymorphism I


### Teacher-Student Activities

In this class, we will learn another concept of object-oriented programming called **Polymorphism**.

Polymorphism is taken from the Greek words poly (many) and morphism (forms). Polymorphism means different forms of the same thing. In programming, the things that can take different forms for different objects are functions and operators.

In Python, there are four types of Polymorphism:

1. Operator Overloading

2. Method Overloading

3. Method Overriding

4. Duck Typing

But we are going to learn only the first three because they are used most of the time.


Let's understand the three different types of Polymorphism with the help of a few examples.


---

#### Activity 1: Operator Overloading^

Operator overloading means extending the meaning of the arithmetic operators (like `+`, `-`, `/` etc.) besides their original function.

**Why do we need operator overloading?**

Recap Python lists class. We learned that arithmetic operators don't work on Python lists in the same way they work on a NumPy array. So if we have to perform such arithmetic operations on list items we have to either convert the list into an array or use the `for` loop. But we can create a whole new numeric data-structure out of the Python list on which we can perform arithmetic operations. We can do this with the help of operator overloading.

**Note:** The code below will throw `TypeError`.


In [ ]:
# S1.1: Create two numeric list of three items each and perform mathematical operations on them
list_1=[1,2,3,4]
# Create two lists
list_2=[5,6,7,8]
# Add the two lists using '+' operator and save it in a variable and print the result
print(list_1+list_2)
# Multiply the two lists using '*' operator and save it in a variable and print the result
print(list_1*4)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
import numpy as np
arr = np.arange(1,10)
arr2 = np.arange(11,20)
print(arr)
print(arr2)
print("additoion of two arrays",arr+arr2)
print(arr)
arr*4

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
additoion of two arrays [12 14 16 18 20 22 24 26 28]
[1 2 3 4 5 6 7 8 9]


array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

As it can be observed in the output, when we try to

- Add corresponding items of two lists, we get a concatenated list.

- Multiply the corresponding items of two lists, we get `TypeError` because the `*` operator is **not defined** for Python lists.


This is because every Python class has some predefined **magic functions** which give meaning to arithmetic operators.

**For Example**
- `+` operator has `__add__()` magic function
- `*` operator has `__mul__()` magic function

**Note:** In Python, the functions having two underscores at prefix and suffix are called magic functions.



In [ ]:
# T1.1: Apply the '__add__()' function on two integers, strings and list objects one-by-one.
print(int.__add__(2,3))
print(str.__add__("h","8"))
print(bool.__add__(True,False))
int.__mul__(2,4)

5
h8
1


8

As you can see, the `__add__()` function in the case of

- Integer objects, add their values

- String objects, concatenates them

- Python list objects, concatenates them

You can use the `__dict__` attribute to get a dictionary of all the attributes and magic methods associated with a class.

In [ ]:
# S1.2: Get the dictionary of all the attributes and magic methods associated with either int, str, float, list etc.
list.__dict__

mappingproxy({'__add__': <slot wrapper '__add__' of 'list' objects>,
              '__contains__': <slot wrapper '__contains__' of 'list' objects>,
              '__delitem__': <slot wrapper '__delitem__' of 'list' objects>,
              '__doc__': 'Built-in mutable sequence.\n\nIf no argument is given, the constructor creates a new empty list.\nThe argument must be an iterable if specified.',
              '__eq__': <slot wrapper '__eq__' of 'list' objects>,
              '__ge__': <slot wrapper '__ge__' of 'list' objects>,
              '__getattribute__': <slot wrapper '__getattribute__' of 'list' objects>,
              '__getitem__': <method '__getitem__' of 'list' objects>,
              '__gt__': <slot wrapper '__gt__' of 'list' objects>,
              '__hash__': None,
              '__iadd__': <slot wrapper '__iadd__' of 'list' objects>,
              '__imul__': <slot wrapper '__imul__' of 'list' objects>,
              '__init__': <slot wrapper '__init__' of 'list' objects>

Now let's get back to our requirement of a new data-structure which behaves like a NumPy array on applying the arithmetic operations such as addition, subtraction, etc.

To get started, let's create a class called `MyList` in which the constructor initialises the `my_list` variable which will contain a list of numeric items.

The class needs to have the following functions:

- > `__add__()`: to **add** the corresponding items two of `MyList` objects one-by-one. It should accept two `MyList` objects for the addition operation.

- > `__sub__()`: to **subtract** the corresponding items two of `MyList` objects one-by-one.

- > `__mul__()`: to **multiply** the corresponding items two of `MyList` objects one-by-one.


- > `__truediv__()`: to **divide** the corresponding items two of `MyList` objects one-by-one.

  > All the above four functions should first check whether both the `MyList` objects have the same length or not.

- > `get_my_list()`: to return the value stored in the `my_list` variable if it has items otherwise throw an error with the `"List does not exist."` message.

**Note:** These methods will work on the current object of the class `MyList` as one operand and will take another object of `MyList` as the second operand, both lists being of the same size. They will return a result list which will also be the object of the `MyList` class.

In [ ]:
# T1.2: Create the 'MyList' class having only the 'my_list' variable, '__add__()' and 'get_my_list()' functions.
class MyList:
  def __init__(self,my_list):
    self.my_list = my_list
  def __add__(self,other_list):#otherlst will act as an object
      if len(self.my_list)!=len(other_list.my_list):
        print("they cannot be added")
      else:
        new_list = [self.my_list[i]+other_list.my_list[i] for i in range(len(self.my_list))]
        return MyList(new_list)

  def get_mylist(self):
    if self.my_list==None:
      return "list is empty"
    else:
      return self.my_list

first_lst = MyList([1,2,3,4,5])
second_lst = MyList([2,2,3,4,5])
new_list = first_lst+second_lst
new_list.get_mylist()







[3, 4, 6, 8, 10]

Similarly, you define the other three magic methods for the `MyList` class. However in the case of `__truediv__()` method, in addition to checking the length of lists, also check whether the divisor list contains `0` or not. If it does contain `0` as an item, then return `"Division by 0 is not possible."` message. Otherwise, the function should perform the division operation.

In [ ]:
# S1.3: Add the remaining magic methods to the 'MyList' class.
class MyList:
  def __init__(self,my_list):
    self.my_list = my_list
  def __add__(self,other_list):#otherlst will act as an object
      if len(self.my_list)!=len(other_list.my_list):
        print("they cannot be added")
      else:
        new_list = [self.my_list[i]+other_list.my_list[i] for i in range(len(self.my_list))]
        return MyList(new_list)
  def __sub__(self,other_list):
      if len(self.my_list)!=len(other_list.my_list):
        print('they cannot be added')
      else:
        new_list= [self.my_list[i]-other_list.my_list[i] for i in range(len(self.my_list))]
        return MyList(new_list)
  def __mul__(self,other_list):
      if len(self.my_list)!=len(other_list.my_list):
        print('they cannot be added')
      else:
        new_list= [self.my_list[i]*other_list.my_list[i] for i in range(len(self.my_list))]
        return MyList(new_list)
  def __truediv__(self,other_list):
      if len(self.my_list)!=len(other_list.my_list):
        print('they cannot be added')
      else:
        new_list= [self.my_list[i]/other_list.my_list[i] for i in range(len(self.my_list))]
        return MyList(new_list)
  def get_mylist(self):
    if self.my_list==None:
      return "list is empty"
    else:
      return self.my_list

first_lst = MyList([1,2,3,4,5])
second_lst = MyList([2,2,3,4,5])
add_list = first_lst+second_lst
sub_list = first_lst-second_lst
mul_list = first_lst*second_lst
div_list = first_lst/second_lst
print(add_list.get_mylist())
print(sub_list.get_mylist())
print(mul_list.get_mylist())
print(div_list.get_mylist())

[3, 4, 6, 8, 10]
[-1, 0, 0, 0, 0]
[2, 4, 9, 16, 25]
[0.5, 1.0, 1.0, 1.0, 1.0]


Now let's test all the methods of the updated `MyList` class, except the `__add__()` method as we have already tested it before.

In [ ]:
# S1.4: Test all the methods of the updated MyList class, except the '__add__()' method.

# 1. Create two objects and call them 'my_lst1' and 'my_lst2'.

# 2. Print the lists stored in both the MyList objects using the 'get_my_list()' function.

# 3. Subtract the items of the MyList objects (created above) using the '-' operator and save the result in a variable.

# 4. Multiply the items of the MyList objects (created above) using the '*' operator and save the result in a variable.

# 5. Divide the items of the MyList objects (created above) using the '/' operator and save the result in a variable.

# 6. Print the object variables created in the above steps


In this way, we have successfully created a new data structure based on a Python list that behaves like a NumPy array on applying the arithmetic operators using the concept of **operator overloading**.

Let's look at the next form of Polymorphism wherein we can alter the functionality of the same method.

---

#### Activity 2: Method Overloading^^

In Python, you can create a method/function that can be called in different ways. You can create a method that has zero, one or more number of parameters. Depending on the method definition, we can call it with zero, one or more arguments.

This process of calling the same method in different ways is called method or function overloading.

To overload a user-defined function in Python, we need to write the logic of the function in such a way that, depending upon the parameters passed, a different piece of code executes inside the function.

Let's understand it with a very nominal example:

Create a class called `Television` having a function `change_channel()`. This function must accept one parameter `channel_name` which is set to `None`. This will give us the option to call `change_channel()` function with or without a parameter.



In [ ]:
# S2.1: Create the 'Television' class having 'change_channel()' method with zero or one argument.
class Television:
  def change_channel(self,channel_name=None):
    if channel_name!= None:
      print("channel name is ",channel_name)
    else:
      print("no channel name")


Let's create an object of the `Television` class and call the `change_channel()` method by providing different inputs.

In [ ]:
# S2.2: Create an object of the 'Television' class and call the 'change_channel()' method by providing different inputs.
tv = Television()
tv.change_channel("star sports")


channel name is  star sports


We can see that by calling the same function with different inputs, we got different outputs for the same object of the `Television` class.

However, if we define multiple functions with the same name, the later one always overloads the prior and hence, we can use only the latest defined method.


To understand this, create the `Television` class again having two variants of the `change_channel()` method, one variant will take one input and the other one doesn't take any input.

**Note:** The code below will throw `TypeError`.

In [ ]:
# T2.1: Create the 'Television' class again having the second variant of 'change_channel()' method.
class Television:
  def change_channel(self,channel_name=None):
    if channel_name!= None:
      print("channel name is ",channel_name)
    else:
      print("no channel name")
  def change_channel(self,channel_name):
   print("the channel name is ",channel_name)
  def change_channel(self):
    print("channel is changed")


As you can see, the latest appearance of the `change_channel()` function doesn't require any input from the user. Hence, the latest appearance has overloaded the previous appearances. Hence, calling any of the previous variant would throw `TypeError`.

Create the `Television` class again having both the variants of `change_channel()` method but swap the positions of both the variants.

**Note:** The code below will throw `TypeError`.

In [ ]:
# T2.2: Create the 'Television' class but swap the positions of the first and the second variant of the 'change_channel()' function.
tv = Television()
tv.change_channel()
#in one class the latest method created with the same name of other methods is executed at runtime


channel is changed


This time, the latest appearance of the `change_channel()` function requires an input. Hence the execution of the first variant gave the `TyepError` because it doesn't accept any input. Hence, the second variant overloaded the first variant.




Let's stop here. In the next class, we will learn another type of polymorphism called **method overriding**.

---

### **Project**
You can now attempt the **Applied Tech. Project 56 - Polymorphism I** on your own.

**Applied Tech. Project 56 - Polymorphism I**: https://colab.research.google.com/drive/1Tms4FUViMTmiOaPPfqSww0HuGv_HRcor?usp=sharing

---